### ISSUE TITLE
MON's and OSD's should not have apostrophes

### ISSUE THREAD

**Issue by dmick** [pcuzner/cephmetrics#13]
I know style guides differ about these, but most of our documentation and more-common modern usage seems to indicate there should be no apostrophe (it connotes possession, which is not what is meant).

http://www.grammarbook.com/punctuation/apostro.asp Rule 6 is one discussion.  The final entry in https://en.oxforddictionaries.com/punctuation/apostrophe is another.  Both seem to agree that it's useful to use apostrophe for plurals in the case of single letters or digits (i.e. "A's" meaning more than one A), presumably because it's so easy to miss the distinction and consider it part of one word rather than a plural.

Anyway I think the majority opinion is 'no apostrophe'.

**Comment by pcuzner** [comment]
I'm siding with the guidance where an apostrophe adds clarity to the text for the reader. There's conflicting guidance these days, and tbh, I didn't want the text to read OSDs - I'm old school mainframe and it just looks too much like OCDS to me.

**Comment by dmick** [comment]
Willing to fight on this.

**Comment by zmc** [comment]
very much agree with @dmick here

**Comment by pcuzner** [comment]
OK - I'm not going to waste cycles on a grammar debate. I'll make the changes
