### ISSUE TITLE
Vonage plugin doesn't work with RH-built grafana

### ISSUE THREAD

**Issue by zmc** [pcuzner/cephmetrics#17]
Haven't diagnosed yet, but:
<img width="197" alt="screen shot 2017-06-21 at 2 50 35 pm" src="https://user-images.githubusercontent.com/58307/27406079-0f32102e-5691-11e7-9350-6c7af9958e39.png">

**Comment by pcuzner** [comment]
isn't this because of the directory name 
You have : Vonage-Grafana_Status_panel
It's looking for : vonage-status-panel

**Comment by zmc** [comment]
Unfortunately that's not the issue. Even using the recommended way:
```
grafana-cli plugins install vonage-status-panel
```
doesn't work.

**Comment by zmc** [comment]
Update: it's a packaging bug. More info soon

**Comment by zmc** [comment]
Logs generated by grafana.com's package, found in `/var/log/grafana/grafana.log`:
```
t=2017-06-15T22:06:02+0000 lvl=info msg="Starting Grafana" logger=main version=4.3.2 commit=ed4d170 compiled=2017-05-31T08:48:16+0000
t=2017-06-15T22:06:02+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-06-15T22:06:02+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-06-15T22:06:02+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-06-15T22:06:02+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-06-15T22:06:02+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-06-15T22:06:02+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-06-15T22:06:02+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2017-06-15T22:06:02+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2017-06-15T22:06:02+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
```

Logs generated by our package, found in `/usr/share/grafana/data/log/grafana.log` (*!*):
```
t=2017-06-21T23:02:57+0000 lvl=info msg="Starting Grafana" logger=main version=4.3.2 commit=unknown-dev compiled=2017-06-21T09:28:40+0000
t=2017-06-21T23:02:57+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2017-06-21T23:02:57+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2017-06-21T23:02:57+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2017-06-21T23:02:57+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2017-06-21T23:02:57+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2017-06-21T23:02:57+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2017-06-21T23:02:57+0000 lvl=info msg="Path Data" logger=settings path=/usr/share/grafana/data
t=2017-06-21T23:02:57+0000 lvl=info msg="Path Logs" logger=settings path=/usr/share/grafana/data/log
t=2017-06-21T23:02:57+0000 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
```

**Comment by zmc** [comment]
@b-ranto could you take a look?

**Comment by zmc** [comment]
fwiw https://github.com/zmc/cephmetrics/commit/320bf7ae67c953ad629705defc11251896939d63 appears to fix it

**Comment by b-ranto** [comment]
I am just wondering, is the grafana package built by me shipping a different config than the upstream build? AFAIK, I am using the same default.ini config as the upstream build.

I know there were some packaging issues with regard to grafana user/group (it could not rewrite the db) and those should be fixed by https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=13492670

However, afaik, I am shipping the same config file as the upstream package. There is one thing with regard to the configs that is different and it is that the upstream package tries to install an old config (.rpmsave) if it can find one which my package won't do (and it even shouldn't) so if you rewrote the config before and removed the package it will "magically" reappear once you reinstall it again.
